#!/bin/sh

# place this in /usr/local/etc/rc.d them chmod +x pia-portforwarding-rc

. /etc/rc.subr

name=pia-portforwarding
rcvar=`set_rcvar`
# modify the path location to pia-pfSense.sh
command=/usr/src/pia-pfSense.sh
start_cmd="/usr/sbin/daemon $command"

load_rc_config $name
run_rc_command "$1"
